:backend: slidy2


== Threads cannot be implemented as a library

http://dl.acm.org/citation.cfm?id=1065042 


**In many environments, multi-threaded code is written in a language that was originally designed 
without thread support (e.g. C)**, to which a library of threading primitives was subsequently added. 
There appears to be a general understanding that this is not the right approach. 
We provide specific arguments that **a pure library approach**, in which the compiler is designed 
independently of threading issues, **cannot guarantee correctness of the resulting code**.
We first review why the approach almost works, and then examine some of the surprising 
behavior it may entail. We further illustrate that there are very simple cases in which 
a pure library-based approach seems incapable of expressing an efficient parallel algorithm.
Our discussion takes place in the context of C with Pthreads, since it is commonly used, 
reasonably well specified, and does not attempt to ensure type-safety, which would entail 
even stronger constraints. The issues we raise are not specific to that context.